configuration:
    database_host: localhost
    database_port: null
    database_name: kinto
    database_user: root
    database_password: root
    local: fr
    template: Twig

security:
    token: 
    expire: 30

connection:
    login: name
    password: password
    activation: true
    remember: false
    session: id|name