configuration:
    default_project: home
    database_host: localhost
    database_port: null
    database_name: test
    database_user: root
    database_password: root
    local: fr
    template: Twig

connection:
    login: name
    password: password
    remember: false
    session: id