configuration:
    database_host: localhost
    database_port: null
    database_name: test
    database_user: root
    database_password: root
    local: fr
    default_project: home
    template: Twig